import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { RefreshProvider } from "@/context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Advance auth",
  description: "Generated by Ankit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" relative min-h-screen bg-[conic-gradient(from_230deg_at_center,_#B2D4E4,_#478BD6,_#003465)] flex flex-row items-center justify-center">
          <ToastContainer />
          <RefreshProvider>{children}</RefreshProvider>
        </div>
      </body>
    </html>
  );
}
